### ISSUE TITLE
Make time of timers editable

### ISSUE THREAD

**Issue by Gnorv** [BlackyHawky/Clock#165] opened 2024-12-17 09:52 UTC
**Is your feature request related to a problem? Please describe.**
Timers are not editable. Once a new timer has been added, only its name can be edited. When I want to do "pasta cooking" for 5 min, I can add a timer for 5 min with that name. If the next day I want to do it for 8 min, I have to make a new timer, and name it again. It would be easier if the time of the first timer was editable.

**Describe the solution you'd like**
Tapping on a timers time while it is in "reset" state (not running and also not paused) prompts you to edit its running time.

**Use case**
See problem description.

**Describe alternatives you've considered**
My current work-around is deleting the old timer, and adding a new one with the desired time. However, that requires me to name it again and requires a significant amount of extra steps. Furthermore, the order of the timers is messed up as the new timer is just added at the top.

**Additional context**
Nothing.

**Comment by BlackyHawky** [comment] 2024-12-17 10:28
Duplicate of #76

> Furthermore, the order of the timers is messed up as the new timer is just added at the top.

The order of timers once reset can be customized in the Timers settings.

**Closed as duplicate** 2024-12-17 10:28 UTC
Labels: duplicate, enhancement, timer
