### ISSUE TITLE
Possibility to deactivate the display of memories from calendar

### ISSUE THREAD

**Issue by mimaiself** [BlackyHawky/Clock#47] opened 2024-06-01 07:23 UTC
**Is your feature request related to a problem? Please describe.**
For me it is very irritating that in the clock view and in the screen saver in addition to the day of the week and date, sometimes an entry (from my calendar) is displayed. Especially since I cannot recognize or display it directly by taping what it is about. For this task I have and prefer a calendar app on my smartphone / tablet - with a detailed memory function. I don't need that in a clock app.

**Describe the solution you'd like**
I would like the opportunity to deactivate the presentation of such calendar entries in the app settings.

**App version**
Latest (current)

**Device (please complete the following information):**
Samsung Galaxy S23 with Android 14 and a Samsung Galaxy Tab A7 Lite with Android 11

**Additional context**
I use two calendar apps on both devices: the original calendar app from Samsung (com.samsung.android.calendar) and a calendar app from F-Droid (com.simplemobiletools.calendar.pro).

**Comment by BlackyHawky** [comment] 2024-06-01 11:20
- Attached you'll find the Deskclock application from LineageOS. Is it the same in this app?

[DeskClock-LineageOS-release.zip](https://github.com/user-attachments/files/15521447/DeskClock-LineageOS-release.zip)

**Comment by mimaiself** [comment] 2024-06-01 17:34
I installed the Lineageos Deskclock in testing. The same behavior there too.

From your comment I conclude that it is not an intended function, a feature.
I will try something with different calendar dates on my devices and then report it to you..

**Comment by BlackyHawky** [comment] 2024-06-01 18:35
> From your comment I conclude that it is not an intended function, a feature.

You're right, I'm not the cause of this behavior at all. That's why unfortunately I won't know how to resolve this. I'm really sorry

> I will try something with different calendar dates on my devices and then report it to you..

Personally, I use [Calendar](https://github.com/FossifyOrg/Calendar) which is a derivative of the [Simple app](https://github.com/SimpleMobileTools/Simple-Calendar). 

In my 2 devices I uninstalled the original app.

In any case, I'm not sure this will solve your problem.

**Comment by mimaiself** [comment] 2024-06-05 23:03
In the last few days I have tried the following:

On the tablet (it is rooted) I deactivated the Samsung calendar app and installed the app you use (Fossify Calendar). Nevertheless, the problem continued to appear.

Also on a third device that I tested (a Galaxy A54 with Android 14) shows your app the same behavior.

Finally, I tested it on my ancient Samsung Galaxy A3 with Android 7. And, what surprise, everything works without any problems. In the clock view (and also in the widgets), only activated alarm times and no appointments from the calendar are displayed.

Another addendum for the problem description: If, for example, I enter an appointment for 8:00 pm to the calendar today and I would like to be reminded at 7:45 pm, this will be in the clock tab of your app (including the alarm icon) to 7:45 pm displayed. After that, although the actual date is at 8:00 pm, the entry has disappeared.

**Comment by BlackyHawky** [comment] 2024-06-15 16:39
I'm closing this topic because it's similar to #61.

Currently, the application takes into account alarms registered in the Android system.

I suggest you to follow this [procedure](https://stackoverflow.com/a/65062762) to check which application is causing the next alarm to be displayed.
By uninstalling (unfortunately) this application, this bug will no longer appear.

To resolve this bug completely the alarms created should be saved in `SharedPreferences` I don't know how to do that. 😬

**Closed as duplicate by BlackyHawky** 2024-06-15 16:39 UTC
Labels: enhancement, alarm, widget
