### ISSUE TITLE
[Galaxy S21 FE] Power off alarm doesn't work

### ISSUE THREAD

**Issue by Unclelon** [BlackyHawky/Clock#158] opened 2024-11-29 05:15 UTC
"On phones with Snapdragon SoC, the alarm will activate even when the device is turned off."

This feature doesn't work here on a Galaxy S21 FE with Android 14 and One UI 6.1!

**Comment by BlackyHawky** [comment] 2024-11-29 09:22
Duplicate of #88

The Readme has been updated but I just noticed that I forgot to update the description for F-Droid/IzzyOnDroid.
I'll close this topic when I've updated this.

**Comment by Unclelon** [comment] 2024-11-29 09:37
Thx👍🏼👋🏼


-------- Ursprüngliche Nachricht --------
Von: BlackyHawky ***@***.***>
Gesendet: 29. November 2024 10:23:04 MEZ
An: BlackyHawky/Clock ***@***.***>
CC: Unclelon ***@***.***>, Author ***@***.***>
Betreff: Re: [BlackyHawky/Clock] Missing Feature 😒 (Issue #158)

Duplicate of #88

The Readme has been updated but I just noticed that I forgot to update the description for F-Droid/IzzyOnDroid.
I'll close this topic when I've updated this.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/BlackyHawky/Clock/issues/158#issuecomment-2507400912
You are receiving this because you authored the thread.

Message ID: ***@***.***>
VG Dirk Runge (ツ)

**Closed as duplicate** 2024-11-30 21:49 UTC
Labels: duplicate, alarm
