### ISSUE TITLE
App crashes since latest update via fdroid has been installed (v2.6)

### ISSUE THREAD

**Issue by Outlet2048** [BlackyHawky/Clock#73] opened 2024-06-29 10:39 UTC
**Describe the bug**
App crashes on open 

**To Reproduce**
- install latest version 
- open app
- app closes 

**Expected behavior**
App doesn't crash

**Screenshots**

**App version**
2.6

**Device (please complete the following information):**
 - Model: OnePlus 9 Pro 
 - OS: OxygenOs 14

**Additional context**

**Comment by BlackyHawky** [comment] 2024-06-29 11:28
@Outlet2048 
Duplicate of #72 

As indicated in the [changelog](https://github.com/BlackyHawky/Clock/releases/tag/2.6), you'll have to reinstall the app due to a change in the database.

**Closed as duplicate by BlackyHawky** 2024-06-29 11:28 UTC
Labels: bug, alarm
