### ISSUE TITLE
App crash at alarm expiration

### ISSUE THREAD

**Issue by timofort** [BlackyHawky/Clock#146] opened 2024-11-25 11:41 UTC
Hello Blacky,

with 2.10, all is fine except alarm expiration with my phone.

When I set an alarm with few time (between 1 min. to few hours), expiration is going well.

Otherwise, an alarm with expiration after many hours results in an app crash (Clock crashed etc ...).

My phone : Google Pixel 4 with Android 13.

Perhaps a compatibility issue with my launcher ? (MS Launcher)

Thanks.

Emmanuel

**Comment by BlackyHawky** [comment] 2024-11-25 11:55
@timofort 
Really sorry for this inconvenience; I am closing this topic because it is a duplicate of #136.

You can download the new version [here](https://github.com/BlackyHawky/Clock/releases/tag/2.10.1), where I unfortunately had to disable the "Set an alarm for a specific date" feature because it was at the root of this major bug.

I hope to find the solution soon.

**Closed as duplicate** 2024-11-25 11:55 UTC
Labels: bug, duplicate, alarm

**Comment by timofort** [comment] 2024-11-25 16:34
Thanks. I will read it.

PS : tu es français ? J'ai vu dans le topic que tu es sur le temps parisien.

Le lun. 25 nov. 2024 à 12:56, BlackyHawky ***@***.***> a
écrit :

**Comment by BlackyHawky** [comment] 2024-11-25 17:29
@timofort 
Oui je suis français 😉
