### ISSUE TITLE
Clock crashes after enabling and disabling lock down mode on samsung

### ISSUE THREAD

**Issue by miphilip** [BlackyHawky/Clock#153] opened 2024-11-27 13:25 UTC
**Describe the bug**
the clock app crashes after using lockdown mode and dismissing the running alarm in notification

**To Reproduce**
1. Set an alarm
2. Enable lock down mode that turns off certain features on lock screen
3. Alarms triggers
4. Unlock phone with password
5. Dismiss alarm from notification

**Expected behavior**
the alarm should be be dismissed 

**App version**
2.10

**Device (please complete the following information):**
 - Model: Samsung Galaxy a32
 - OS: Android 13

**Additional context**
[crash.log](https://github.com/user-attachments/files/17934886/crash.log)

**Comment by BlackyHawky** [comment] 2024-11-27 13:55
@miphilip 
Really sorry for this inconvenience; I am closing this topic because it is a duplicate of #136.

You can download the new version [here](https://github.com/BlackyHawky/Clock/releases/tag/2.10.1), where I unfortunately had to disable the "Set an alarm for a specific date" feature because it was at the root of this major bug.

I hope to find the solution soon.

**Closed as duplicate** 2024-11-27 13:56 UTC
Labels: bug, duplicate, alarm

**Comment by miphilip** [comment] 2024-11-27 14:12
Thanks i appreciate your work
