### ISSUE TITLE
freeze when alarm rings, app doesnt open

### ISSUE THREAD

**Issue by secretmango** [BlackyHawky/Clock#143] opened 2024-11-25 08:11 UTC
[Error in Uhr 2c6fcfd12cac.txt](https://github.com/user-attachments/files/17899544/Error.in.Uhr.2c6fcfd12cac.txt)

GrapheneOS, Pixel 6a

Version 2.10.

When the alarm rings the fullscreen menu doesnt react.

There is no notification in the swipe-down-menu

Clicking the clock icon it doesnt open

I rebooted to turn the alarm off, the same happened a few minutes later.

The logs repeat this over and over

```
com.best.deskclock.alarms.AlarmStateManager.registerInstance(AlarmStateManager.java:634)
  at com.best.deskclock.alarms.AlarmStateManager.updateParentAlarm(AlarmStateManager.java:227)
  at com.best.deskclock.alarms.AlarmStateManager.setMissedState(AlarmStateManager.java:447)
  at com.best.deskclock.alarms.AlarmStateManager.registerInstance(AlarmStateManager.java:634)
  at com.best.deskclock.alarms.AlarmStateManager.updateParentAlarm(AlarmStateManager.java:227)
```

**Comment by BlackyHawky** [comment] 2024-11-25 08:35
@secretmango 
Really sorry for this inconvenience; I am closing this topic because it is a duplicate of #136.

You can download the new version [here](https://github.com/BlackyHawky/Clock/releases/tag/2.10.1), where I unfortunately had to disable the "Set an alarm for a specific date" feature because it was at the root of this major bug.

I hope to find the solution soon.

**Closed as duplicate** 2024-11-25 08:35 UTC
Labels: bug, duplicate, alarm
