### ISSUE TITLE
App freezes when trying to dismiss an alarm

### ISSUE THREAD

**Issue by cyberdust2k** [BlackyHawky/Clock#159] opened 2024-12-03 04:55 UTC
**Describe the bug**

If a alarm rings and I try to dismiss the alarm by swiping right, the app gets unresponsive snd I have to force close it.

**To Reproduce**

1. set an alarm
2. wait for it to fire
3. dismiss it by swiping right
**Expected behavior**

Dismissing the alarm should dismiss the alarm properly and end the alarm ringtone
**Screenshots**

**App version**

2.10
**Device (please complete the following information):**
 - Model: 
 - OS: 
Pixel 9 Pro
GrapheneOS Android 15
**Additional context**

**Comment by BlackyHawky** [comment] 2024-12-03 06:06
@cyberdust2k 
Hi,

Really sorry for this inconvenience; I am closing this topic because it is a duplicate of #136.

You can download the new version [here](https://github.com/BlackyHawky/Clock/releases/tag/2.10.1), where I unfortunately had to disable the "Set an alarm for a specific date" feature because it was at the root of this major bug.

**Closed as duplicate** 2024-12-03 06:06 UTC
Labels: bug, duplicate, alarm

**Comment by cyberdust2k** [comment] 2024-12-03 07:13
Ah, my bad, apparently Obtainium didn't catch that update. Thanks for letting me know.
