### ISSUE TITLE
Alarms don't fire after latest update

### ISSUE THREAD

**Issue by florianhenig** [BlackyHawky/Clock#141] opened 2024-11-24 19:19 UTC
**Describe the bug**
After the latest update (2.10) alarms don't fire anymore. 

**To Reproduce**
Hard to tell how to reproduce.
1. I initially installed v. 2.09
2. I setup my alarms.
3. They worked just fine.
4. Updated to the latest version 2.10
5. Alarms not working anymore. 

**Expected behavior**
Alarms fire at the time they are set up to. 

**App version**
2.10 github release

**Device (please complete the following information):**
 - Model: Google Pixel 6a
 - OS: GrapheneOS (up to date); Android 15

**Additional context**
Before this issue I had a couple of times problems with dismissing alarms (2.10). The lockscreen overlay wasn't responding and an "app not responding" message was shown, asking me to force stop the app or wait.

**Comment by BlackyHawky** [comment] 2024-11-24 21:49
@florianhenig 
Really sorry for this inconvenience; I am closing this topic because it is a duplicate of #136.
I am currently working to provide a version without this bug.

**Closed as duplicate by BlackyHawky** 2024-11-24 21:49 UTC
Labels: bug, duplicate, alarm

**Comment by BlackyHawky** [comment] 2024-11-25 08:37
@florianhenig
You can download the new version [here](https://github.com/BlackyHawky/Clock/releases/tag/2.10.1), where I unfortunately had to disable the "Set an alarm for a specific date" feature because it was at the root of this major bug.

I hope to find the solution soon.

**Comment by florianhenig** [comment] 2024-11-25 09:43
> @florianhenig Really sorry for this inconvenience; I am closing this topic because it is a duplicate of #136. I am currently working to provide a version without this bug.

I'm sorry for opening a duplicate bug report. I'm pretty sure that I didn't find anything similar.
